"""
Django settings for editapp project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from dotenv import load_dotenv
#　pip install python-dotenv　として波線を消す
#これで消えぬ時は　Ctrl + Shift + P　→「Python: Select Interpreter」を選択
#     →   python-dotenv をインストールした仮想環境（venvなど）を1つ1つ消えるまで選択
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u_i22yuz$zq#xkq5*n1$1-ftc5wm7#9-$9kz6elhu&7z)1tjt1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'edit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'editapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [],
        'DIRS': [BASE_DIR / 'templates'],  # ← ここが [BASE_DIR / 'templates'] 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'editapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

LOGIN_URL = 'login'#未ログイン時飛ばされるところ
LOGIN_REDIRECT_URL = '/'  # ログインが成功した後に自動で飛ばす先（TOPページなど）

#LOGOUT_REDIRECT_URL = 'login'#ログアウトした後に飛ばす先（ログイン画面に戻すのが一般的）
LOGIN_REDIRECT_URL = 'post_list' # ここが 'login' になっていると無限ループします

#LOGOUT_REDIRECT_URL='login'#これによりボタンを押すと内部でログアウト処理が走り、自動的にログイン画面（または指定したページ）へ移動して「未ログイン状態」
#正しくは、「ログアウトボタン（POST送信）を押してログアウト処理が終わった瞬間に、自動で『ログイン画面』へ飛ばしてくれる設定」
#{%url 'login'%}のボタン押すとログアウトになるわけではない

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = '://gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# 送信に使用するGmailアカウント
EMAIL_HOST_USER = 'あなたのメールアドレス@gmail.com'

# Googleアカウントで発行した「アプリパスワード」を入力します（通常のパスワードではありません）
EMAIL_HOST_PASSWORD = 'ここに16桁のアプリパスワードを入力'

# デフォルトの送信元アドレス（任意）
DEFAULT_FROM_EMAIL = 'admin@1q1q.xyz'